name: Kingdom Hearts Birth by Sleep Melding Calculator
url: https://khbbsmelding.com
permalink: /:title
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
include:
  - ads.txt
  - CNAME